kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-media"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
